// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avajpkfwysufvfweuonn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2YWpwa2Z3eXN1ZnZmd2V1b25uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MjIwNTcsImV4cCI6MjA2ODM5ODA1N30.9ZlW3XDn9OcC6nMiQOZHxxkcAvb9MGSzgfVvHgA7nTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});